### ISSUE TITLE
[BUG] Providing collat-specific EPS is overwritten by watchdog.eps value

### ISSUE THREAD

**Issue by TechDufus** [TechDufus/FluxNodeInstall#68]
### Environment

Self-Hosted

### System

Ubuntu 22.04 LTS

### Version

main

### Describe the problem

With the following user.yml vars, it produces the below watchdog/config.js file. The EPS closest to the collateral should win.
```yaml
user:
  dufus:
    zelid: 123123
    kda: '123123'
    identity_key: '123123'
    force_new_chain: false
    watchdog:
      flux_update: '1'
      daemon_update: '1'
      bench_update: '1'
      eps: '180'
      discord_webhook: 'https://123.com'
      discord_ping: '321321'
    t0:
      collateral_tx: 'collat-0'
    t1:
      collateral_tx: 'collat-1'
    t2:
      collateral_tx: 'collat-2'
    t3:
      collateral_tx: 'collat-3'
      eps: '90'
```

`~/watchdog/config.js`
```js
module.exports = {
  label:              'cumulus0',
  tier_eps_min:       '180',
  zelflux_update:     '1',
  zelcash_update:     '1',
  zelbench_update:    '1',
  action:             '1',
  ping:               '321321',
  web_hook_url:       'https://123.com',
  telegram_alert:     '0',
  telegram_bot_token: '0',
  telegram_chat_id:   '0'
}
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using the latest version of FluxNodeInstall
- [X] You've checked that this [issue hasn't already been raised](https://github.com/techdufus/FluxNodeInstall/issues?q=is%3Aissue)
- [X] You agree to the [code of conduct](https://github.com/techdufus/FluxNodeInstall/blob/main/.github/CODE_OF_CONDUCT.md)
